garage/src/Entity/AdminReponse.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdminReponseRepository")
 */
class AdminReponse
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $messsage;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="adminReponses")
     */
    private $user_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $heur;



    public function __construct()
    {
        date_default_timezone_set('Europe/Paris');
        $this->heur = date('d/m/Y à H:i:s',time());
    }

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getMesssage(): ?string
    {
        return $this->messsage;
    }

    public function setMesssage(string $messsage): self
    {
        $this->messsage = $messsage;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getHeur(): ?string
    {
        return $this->heur;
    }

    public function setHeur(string $heur): self
    {
        $this->heur = $heur;

        return $this;
    }


}

garage/src/Entity/RendezVous.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RendezVousRepository")
 */
class RendezVous
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="rendezVouses")
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $jour;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $heurDepart;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $heurFin;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $sujet;

    /**
     * @ORM\Column(type="text", length=255)
     */
    private $message;

    public function __construct()
    {
        date_default_timezone_set('Europe/Paris');
        $this->date = date('d/m/Y à H:i:s',time());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getJour(): ?string
    {
        return $this->jour;
    }

    public function setJour(string $jour): self
    {
        $this->jour = $jour;

        return $this;
    }

    public function getHeurDepart(): ?string
    {
        return $this->heurDepart;
    }

    public function setHeurDepart(string $heurDepart): self
    {
        $this->heurDepart = $heurDepart;

        return $this;
    }

    public function getHeurFin(): ?string
    {
        return $this->heurFin;
    }

    public function setHeurFin(string $heurFin): self
    {
        $this->heurFin = $heurFin;

        return $this;
    }

    public function getDate(): ?string
    {
        return $this->date;
    }

    public function setDate(string $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getSujet(): ?string
    {
        return $this->sujet;
    }

    public function setSujet(string $sujet): self
    {
        $this->sujet = $sujet;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }
}

garage/src/Form/RendezVousType.php
<?php

namespace App\Form;

use App\Entity\RendezVous;
use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\User\UserInterface;

class RendezVousType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('jour', TextType::class,[
                'label' => 'Date',
                'attr' => [
                    'class' => 'datepicker-here input',
                    'id' => 'test',
                    'data-timepicker' => 'true',
                    'data-language' => 'fr'

                ]
            ])
            ->add('sujet',TextType::class,[
                'attr' =>['placeholder' => 'Ex:Revision,vidange...',
                    'class' => 'input']
            ])
        ->add('message', TextareaType::class,[
            'attr' =>['placeholder' => 'Decrivez votre problème',
                'class' => 'input']
        ]);

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => RendezVous::class,
        ]);
    }
}

garage/src/Controller/RendezVousController.php
<?php

namespace App\Controller;

use App\Entity\RendezVous;
use App\Entity\AdminReponse;
use App\Form\AdminReponseType;
use App\Form\RendezVousType;
use App\Repository\AdminReponseRepository;
use App\Repository\RendezVousRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/rendez/vous")
 */
class RendezVousController extends AbstractController
{

    //permet de faire la demande de rendez-vous
    /**
     * @Route("/user", name="rendez_vous_index", methods={"GET"})
     * @param RendezVousRepository $rendezVousRepository
     * @param AdminReponseRepository $adminReponseRepository
     * @return Response
     */
    public function index(RendezVousRepository $rendezVousRepository, AdminReponseRepository $adminReponseRepository): Response
    {
        $user = $this->getUser();

        return $this->render('rendez_vous/index.html.twig', [
            //Permet de bloquer le contenue a l'utililaseur uniquement

            'rendez_vouses' => $rendezVousRepository->findBy(["User"=>$user]),
            'AdminReponses'=> $adminReponseRepository->findBy(['user_id'=>$user]),
        ]);
    }



    /**
     * @param RendezVousRepository $rendezVousRepository
     * @return Response
     * @Route("/admin", name="rendez_vous_admin", methods={"GET"})
     */
    public function indexAdmin(RendezVousRepository $rendezVousRepository, AdminReponseRepository $adminReponseRepository): Response
    {
        return $this->render('rendez_vous/index.html.twig', [
            //permet de d'afficher tout les rendez-vous pour l'admin

            'rendez_vouses' => $rendezVousRepository->findAll(),
            'AdminReponses'=> $adminReponseRepository->findAll()
        ]);
    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     * @Route("/admin/new/{id}" ,name="rendez_vous_newAdmin", methods={"GET","POST"})
     */
    public function newResponse(Request $request, RendezVous $rendezVous): Response
    {
        //on créé le formulaire

        $AdminReponse = new AdminReponse();
        $form = $this->createForm(AdminReponseType::class,$AdminReponse);
        $form->handleRequest($request);

        //on verifie si il est valide
        if($form->isSubmitted() && $form->isValid()){

           //recuperé l'utilisateur connecter
            $user = $this->getUser();
            $user_email = $user->getEmail();
          /*  $AdminReponse->setCreatedAt(new\DateTime(time()));*/
            $AdminReponse->setUserId($rendezVous->getUser());

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($AdminReponse);
            $entityManager->flush();

$this->addFlash('success', 'Message Envoyez ');

            return $this->redirectToRoute('rendez_vous_index');
        }
        return $this->render('rendez_vous/newAdmin.html.twig', [
            'reponse' => $AdminReponse,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/new", name="rendez_vous_new", methods={"GET","POST"})
     */
    public function new(Request $request, RendezVousRepository $rendezVousRepository): Response
    {
        $rendezVous = new RendezVous();
        $form = $this->createForm(RendezVousType::class, $rendezVous);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $this->getUser();
            $user_email = $user->getEmail();
            $rendezVous->setUser($this->getUser());
            // Envoie email
            //configurer le swift avec l'email souhaiter

            $transport = (new \Swift_SmtpTransport('smtp.gmail.com',465,'ssl'))
                ->setUsername('garagepilet@gmail.com')
                ->setPassword('b@bmarley789');

            $mailer = new\Swift_Mailer($transport);
         //configuré l'affichage du mail
            //l'envoie le receveur
            $message = (new\Swift_Message('Garage Pilet'))
                ->setSubject('Message de rendez-vous')
                ->setFrom('garagepilet@gmail.com') //renplacer ar user-email
                ->setTo('garagepilet@gmail.com')
                ->setBody(
                    $this->renderView(
                        'content/rendez_vous.html.twig',[
                            'rendezvouses' => $rendezVous,
                            'User' => $user

                        ]
                    ),
                    'text/html'
                );
            //on envoie
            $mailer->send($message);

            $this->redirectToRoute('content_index');



            // recup user connecte

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($rendezVous);
            $entityManager->flush();

            return $this->redirectToRoute('rendez_vous_index');
        }

        return $this->render('rendez_vous/new.html.twig', [
            'rendez_vous' => $rendezVous,
            'form' => $form->createView(),
        ]);
    }



    /**
     * @Route("/{id}", name="rendez_vous_show", methods={"GET"})
     */
    public function show(RendezVous $rendezVous): Response
    {
        return $this->render('rendez_vous/show.html.twig', [
            'rendez_vous' => $rendezVous,
        ]);
    }

    /**
     * @param AdminReponse $adminReponse
     * @return Response
     * @Route("/show/{id}",name="reponse_rendez_vous",methods={"GET"})
     */
    public function showAdmin(AdminReponse $adminReponse): Response
    {
        return $this->render('rendez_vous/showAdmin.html.twig',[
            'AdminReponse'=> $adminReponse
        ]);
    }

    /**
     * @Route("/{id}/edit", name="rendez_vous_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, RendezVous $rendezVous): Response
    {
        $form = $this->createForm(RendezVousType::class, $rendezVous);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('rendez_vous_index', [
                'id' => $rendezVous->getId(),
            ]);
        }

        return $this->render('rendez_vous/edit.html.twig', [
            'rendez_vous' => $rendezVous,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="rendez_vous_delete", methods={"DELETE"})
     */
    public function delete(Request $request, RendezVous $rendezVous): Response
    {
        if ($this->isCsrfTokenValid('delete'.$rendezVous->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($rendezVous);
            $entityManager->flush();
        }

        return $this->redirectToRoute('rendez_vous_index');
    }
}

garage/templates/rendez_vous/_delete_form.html.twig
<form method="post" action="{{ path('rendez_vous_delete', {'id': rendez_vous.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ rendez_vous.id) }}">
    <button class="btn">Delete</button>
</form>

garage/templates/rendez_vous/_form.html.twig
<style>

</style>
<!-- Include English language -->


<div>{{ form_start(form)  }}</div>
<div>   {{ form_widget(form) }}</div>

<button class="btn btn-primary" style="margin-left: 3%; margin-top: 1%;">valider</button>

<div id="push">{{ form_end(form) }}</div>





<script>// Initialization
    $('.datepicker-here').datepicker({
        language: 'fr',
        minDate: new Date()
        // Now can select only dates, which goes after today
    });
    var disabledDays = [0, 6];


//function qui permet d'enlever les jour passer

    $('.datepicker-here').datepicker({
        language: 'fr',
        onRenderCell: function (date, cellType) {
            if (cellType == 'day') {
                var day = date.getDay(),
                    isDisabled = disabledDays.indexOf(day) != -1;

                return {
                    disabled: isDisabled
                }
            }
        }
    })
    $('.datepicker-here').datepicker({
        timepicker: true,
        language: 'fr',

        minHours: 9 ,
        maxHours: 19,
        onSelect: function (fd, d, picker) {
            // Do nothing if selection was cleared
            if (!d) return;

            var day = d.getDay();

            // Trigger only if date is changed
            if (prevDay != undefined && prevDay == day) return;
            prevDay = day;

            // If chosen day is Saturday or Sunday when set
            // hour value for weekends, else restore defaults
            if (day == 6 || day == 0) {
                picker.update({
                    minHours: 10,
                    maxHours: 16
                })
            } else {
                picker.update({
                    minHours: 9,
                    maxHours: 18
                })
            }
        }
    });



</script>

garage/templates/rendez_vous/_formAdmin.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

garage/templates/rendez_vous/admin.html.twig
{% extends 'base.html.twig' %}

{% block title %}RendezVous admin{% endblock %}

{% block body %}

    <style>


        .containerRendezVous {
            text-align: center;
            background-color: lightslategray;
            width: 40%;
            margin-top: 3%;
            padding: 2% 2% 2% 2%;
            box-shadow: 5px 5px 3px 0 #5dacd7;

        }

        .containerTotal {
            width: 100%;
            display: flex;
            flex-direction: row;
            justify-content: center;


        }


        .message {
            margin-top: 2%;


        }

        .detailText {
            text-decoration: none;
            color: wheat;
            cursor: pointer;
        }

        .detailMessage {
            margin-top: 3%;

            font-weight: bold;


        }
    </style>

    <h1 class="titleAccueil">Demande de Rendez-vous</h1>



    <body>
    {% for rendez_vous in rendez_vouses %}
        <div class="containerTotal">
            {% for message in app.flashes('success') %}
                <div style="color:black;width:200px;">{{ message }}</div>
            {% endfor %}

            <div class="containerRendezVous">
                <div class="message"><strong>Message de :</strong> {{ rendez_vous.user }}</div>

                <!-- <div id="rendezVous" class="containerRendezVous">
            <div class="jour">Rendez-vous : {{ rendez_vous.jour }}</div>
            <div class="heurDepart">{{ rendez_vous.heurDepart }}</div>
            <div class="heurFin">{{ rendez_vous.heurFin }}</div>-->


                <div class="detailMessage"><a class="detailText"
                                              href="{{ path('rendez_vous_show', {'id': rendez_vous.id}) }}">Voir le
                        message complet</a></div>
            </div>
        </div>
        <!--<a href="{{ path('rendez_vous_edit', {'id': rendez_vous.id}) }}">edit</a>-->


    {% else %}
        <tr>
            <td colspan="5">no records found</td>
        </tr>
    {% endfor %}
    </body>
    <script>


    </script>


    <div class="stockCreation"><a class="Crée" href="{{ path('rendez_vous_new') }}">Envoyer une reponse</a></div>
{% endblock %}

garage/templates/rendez_vous/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit RendezVous{% endblock %}

{% block body %}
    <h1>Edit RendezVous</h1>

    {{ include('rendez_vous/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('rendez_vous_index') }}">back to list</a>

    {{ include('rendez_vous/_delete_form.html.twig') }}
{% endblock %}

garage/templates/rendez_vous/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}RendezVous index{% endblock %}

{% block body %}


    <style>


        .containerRendezVous {
            text-align: center;
            background-color: lightslategray;
            width: 40%;
            margin-top: 3%;
            padding: 2% 2% 2% 2%;
            box-shadow: 5px 5px 3px 0 #5dacd7;

        }

        .containerTotal {
            width: 100%;
            display: flex;
            flex-direction: row;
            justify-content: center;


        }


        .message {
            margin-top: 2%;


        }

        .detailText {
            text-decoration: none;
            color: wheat;
            cursor: pointer;
        }

        .detailMessage {
            margin-top: 3%;

            font-weight: bold;


        }
    </style>

    <h1 class="titleAccueil">Demande de Rendez-vous</h1>



    <body>
    {% for message in app.flashes('success') %}
        <div style="color:black;width:200px;">{{ message }}</div>
    {% endfor %}
    {% for rendez_vous in rendez_vouses %}
        <div class="containerTotal">
            {% if is_granted('ROLE_USER') %}
                <div class="containerRendezVous">
                    <div class="message"><strong>Message de :</strong> {{ rendez_vous.user }}</div>
                    <div class="message"><strong>{{ rendez_vous.date }}</strong></div>




                    <div class="detailMessage"><a class="detailText"
                                                  href="{{ path('rendez_vous_show', {'id': rendez_vous.id}) }}">Voir le
                            message complet</a></div>
                </div>
            {% endif %}
            {% if is_granted('ROLE_ADMIN') %}
                <div class="containerRendezVous">
                    <div class="message"><strong>Message de :</strong> {{ rendez_vous.user }}</div>
                    <div class="message"><strong>{{ rendez_vous.date }}</strong></div>



                    <div class="detailMessage"><a class="detailText"
                                                  href="{{ path('rendez_vous_show', {'id': rendez_vous.id}) }}">Voir le
                            message complet</a></div>
                </div>
            {% endif %}
        </div>
        <!--<a href="{{ path('rendez_vous_edit', {'id': rendez_vous.id}) }}">edit</a>-->


    {% else %}
        <tr>
            <td colspan="5">no records found</td>
        </tr>
    {% endfor %}
    </body>
    <script>


    </script>


    <div class="stockCreation"><a class="Crée" href="{{ path('rendez_vous_new') }}">Faire une demande de
            Rendez-vous</a></div>
    <h2>Mes reponse au Rendez-vous</h2>
    {% for AdminReponse in AdminReponses %}

        <div class="containerRendezVous">
            <div>{{ AdminReponse.userId }}</div>

            <div>{{ AdminReponse.heur }}</div>
            <div class="detailMessage"><a class="detailText"
                                          href="{{ path('reponse_rendez_vous', {'id': AdminReponse.id}) }}">Voir le
                    message complet</a></div>
        </div>
        </div>

    {% endfor %}

{% endblock %}

garage/templates/rendez_vous/new.html.twig
{% extends 'base.html.twig' %}

{% block title %} RendezVous{% endblock %}

{% block body %}
    <style>

    </style>
    <div style="height: 14vh;"></div>
    <h1 class="titre">Demandez un Rendez-Vous</h1>

    {{ include('rendez_vous/_form.html.twig') }}

    <a style="margin-top: 1%; margin-left: 3%;" class="btn btn-outline-primary" href="{{ path('rendez_vous_index') }}">Retour a l'accueil</a>
{% endblock %}

garage/templates/rendez_vous/newAdmin.html.twig
{% extends 'base.html.twig' %}

{% block title %}New RendezVous{% endblock %}

{% block body %}

    <h1>Repondre au rendez-vous</h1>


   <div id="my-element"> {{ form_start(form) }}</div>
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
    {{ form_end(form) }}

{#{{ include('rendez_vous/_formAdmin.html.twig') }}#}

    <a href="{{ path('rendez_vous_admin') }}">Retour a la list des rendez-vous</a>

{% endblock %}

garage/templates/rendez_vous/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}RendezVous{% endblock %}

{% block body %}
    <div style="height:14vh;"></div>
    <h1>RendezVous</h1>
    <style>

    </style>


<div class="containerRendezVous">

                <div><strong>Jour du rendez-vous : </strong>{{ rendez_vous.jour }}</div>



                <div><strong>Sujet du rendez-vous:</strong>{{ rendez_vous.sujet }}</div>
    <div><strong>Message</strong>{{ rendez_vous.message }}</div>





</div>
    <a href="{{ path('rendez_vous_index') }}">Retour au Demande de rendez-vous</a>

   <!-- <a href="{{ path('rendez_vous_edit', {'id': rendez_vous.id}) }}">edit</a>-->
    <a href="{{ path('rendez_vous_newAdmin',{'id': rendez_vous.id}) }}">Repondre au rendez-vous</a>
  {#  {{ include('rendez_vous/newAdmin.html.twig') }} #}
    {{ include('rendez_vous/_delete_form.html.twig') }}
{% endblock %}

garage/templates/rendez_vous/showAdmin.html.twig
{% extends 'base.html.twig' %}

{% block title %}RendezVous{% endblock %}

{% block body %}
    <style>
        .containerRendezVous{
            margin-top: 10%;
            text-align: center;
            display: flex;
            flex-direction: row;
            justify-content: center;

        }
    </style>
    <h1>RendezVous</h1>



    <div class="containerRendezVous">
        <div style="width: 60%;
    background-color: cadetblue;
    padding: 10px 10px 10px 10px;
 border: solid 5px black;">
<h2><strong>Sujet:</strong> Réponse a la demande de devis </h2>
       <div><strong>Message:     </strong>{{ AdminReponse.messsage }}</div>
    </div>
    </div>



{% endblock %}