garage/src/Entity/AdminReponseDevis.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdminReponseDevisRepository")
 */
class AdminReponseDevis
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="adminReponseDevis")
     */
    private $user;

    /**
     * @ORM\Column(type="text")
     */
    private $Message;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $estimation;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->Message;
    }

    public function setMessage(string $Message): self
    {
        $this->Message = $Message;

        return $this;
    }

    public function getEstimation(): ?string
    {
        return $this->estimation;
    }

    public function setEstimation(string $estimation): self
    {
        $this->estimation = $estimation;

        return $this;
    }
}

garage/src/Entity/Devis.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DevisRepository")
 */
class Devis
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $voiture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $marque;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $modele;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $informationComplementaire;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Numero;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $date;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="devis")
     */
    private $user;

    public function __construct()
    {
        date_default_timezone_set('Europe/Paris');
        $this->date = date('d/m/Y à H:i:s',time());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getVoiture(): ?string
    {
        return $this->voiture;
    }

    public function setVoiture(string $voiture): self
    {
        $this->voiture = $voiture;

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->modele;
    }

    public function setModele(string $modele): self
    {
        $this->modele = $modele;

        return $this;
    }

    public function getInformationComplementaire(): ?string
    {
        return $this->informationComplementaire;
    }

    public function setInformationComplementaire(?string $informationComplementaire): self
    {
        $this->informationComplementaire = $informationComplementaire;

        return $this;
    }

    public function getNumero(): ?string
    {
        return $this->Numero;
    }

    public function setNumero(?string $Numero): self
    {
        $this->Numero = $Numero;

        return $this;
    }

    public function getDate(): ?string
    {
        return $this->date;
    }

    public function setDate(string $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

garage/src/Form/DevisType.php
<?php

namespace App\Form;

use App\Entity\Devis;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DevisType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('voiture')
            ->add('marque')
            ->add('modele')
            ->add('informationComplementaire')
            ->add('Numero')

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Devis::class,
        ]);
    }
}

garage/src/Controller/DevisController.php
<?php

namespace App\Controller;

use App\Entity\AdminReponse;
use App\Entity\AdminReponseDevis;
use App\Entity\Devis;
use App\Form\AdminReponseDevisType;
use App\Form\DevisType;
use App\Repository\AdminReponseDevisRepository;
use App\Repository\DevisRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/devis")
 */
class DevisController extends AbstractController
{
    /**
     * @Route("/", name="devis_index", methods={"GET"})
     */
    public function index(DevisRepository $devisRepository,AdminReponseDevisRepository $adminReponseDevisRepository): Response
    {
        $user = $this->getUser();
        return $this->render('devis/index.html.twig', [
            'devis' => $devisRepository->findBy(["user"=>$user]),
            'AdminReponseDevi'=> $adminReponseDevisRepository->findBy(['user'=>$user]),
        ]);
    }

    /**
     * @param DevisRepository $devisRepository
     * @param AdminReponseDevisRepository $adminReponseDevisRepository
     * @return Response
     * @Route("/admin",name="devis_admin",methods={"GET"})
     */
    public function indexAdminDevis(DevisRepository $devisRepository,AdminReponseDevisRepository $adminReponseDevisRepository ){
        return $this->render('devis/index.html.twig',[
           //tout afficher les devis pour l'admin
            'devis' => $devisRepository->findAll(),
            'AdminReponseDevi' => $adminReponseDevisRepository->findAll()
        ]);
    }

    /**
     * @param Request $request
     * @param Devis $devis
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     * @Route("/admin/{id}",name="devis_newadmin",methods={"GET","POST"})
     */
    public function ReponseDevis(Request $request, Devis $devis){

        $AdminDevis = new AdminReponseDevis();
       $form = $this->createForm(AdminReponseDevisType::class ,$AdminDevis);
       $form->handleRequest($request);

       if ($form->isSubmitted() && $form->isValid()){
           $user = $this->getUser();
           $user_email = $user->getEmail();
           $AdminDevis->setUser($devis->getUser());

           $transport =(new \Swift_SmtpTransport('smtp.gmail.com',465,'ssl'))
               ->setUsername('garagepilet@gmail.com')
               ->setPassword('b@bmarley789');

           $mailer = new\Swift_Mailer($transport);

           $message = (new\Swift_Message('Garage Pilet'))
               ->setSubject('Reponse du Garage pilet')
               ->setFrom('garagepilet@gmail.com')
               ->setTo($user_email)
               ->setBody(
                   $this->renderView(
                       'devis/reponseDevis.html.twig' ,[
                           'AdminReponseDevi' =>$AdminDevis,
                           'user' => $user
                   ]
                   ),
                   'text/html'
               );
           $mailer->send($message);





           $entityManager = $this->getDoctrine()->getManager();
           $entityManager->persist($AdminDevis);
           $entityManager->flush();

          return $this->redirectToRoute('devis_index');
       }



           return $this->render('devis/newAdmin.html.twig',[
               'AdminReponseDevi' => $AdminDevis,
               'form' => $form->createView(),
           ]);


    }

    /**
     * @param AdminReponseDevis $adminReponseDevis
     * @return Response
     * @Route("/show/{id}",name="reponse_devis",methods={"GET"})
     */
    public function showDevisAdmin(AdminReponseDevis $adminReponseDevis): Response
    {
        return $this->render('devis/showDevisAdmin.html.twig',[
            'AdminReponseDevis' => $adminReponseDevis
        ]);
    }


    /**
     * @Route("/new", name="devis_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $devi = new Devis();

        $form = $this->createForm(DevisType::class, $devi);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
           $user = $this->getUser();
           $user_email = $user->getEmail();

            $devi->setUser($this->getUser());
            //Envoie email
            $transport = (new \Swift_SmtpTransport('smtp.gmail.com',465,'ssl'))
                ->setUsername('garagepilet@gmail.com')
                ->setPassword('b@bmarley789');

            $mailer = new\Swift_Mailer($transport);

            $message = (new\Swift_Message('Garage Pilet'))
                ->setSubject('Demande de devis')
                ->setFrom( $user_email)
                ->setTo('garagepilet@gmail.com')
                ->setBody(
                    $this->renderView(
                        'devis/EmailDevis.html.twig',[
                            'devi' => $devi,
                            'User' => $user

                        ]
                    ),
                    'text/html'
                );
            $mailer->send($message);

            $this->redirectToRoute('devis_index');
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($devi);
            $entityManager->flush();

            return $this->redirectToRoute('devis_index');
        }

        return $this->render('devis/new.html.twig', [
            'devi' => $devi,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="devis_show", methods={"GET"})
     */
    public function show(Devis $devi): Response
    {
        return $this->render('devis/show.html.twig', [
            'devi' => $devi,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="devis_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Devis $devi): Response
    {
        $form = $this->createForm(DevisType::class, $devi);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('devis_index', [
                'id' => $devi->getId(),
            ]);
        }

        return $this->render('devis/edit.html.twig', [
            'devi' => $devi,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="devis_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Devis $devi): Response
    {
        if ($this->isCsrfTokenValid('delete'.$devi->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($devi);
            $entityManager->flush();
        }

        return $this->redirectToRoute('devis_index');
    }
}

garage/templates/devis/EmailDevis.html.twig
{% block body  %}

    <tbody>

    <div class="containerDevis container">
        <div class="styleMessage">
            <div class="category"><strong>Expediteur: </strong>{{ devi.user }}</div>
            <div class="category"><strong>Voiture: </strong>{{ devi.voiture }}</div>
            <div class="category"><strong>Marque: </strong>{{ devi.marque }}</div>
            <div class="category"><strong>Modèle: </strong>{{ devi.modele }}</div>
            {% if devi.numero is null %}


            {% else  %}
                <div class="category"><strong>Numéro: </strong>{{ devi.numero }}</div>
            {% endif %}

            <div class="category"><strong>Envoyez le: </strong>{{ devi.date }}</div>
            <div class="category"><strong>Problème technique:  </strong><br>{{ devi.informationComplementaire }}</div>



        </div>
    </div>

    </tbody>

{% endblock %}

garage/templates/devis/_delete_form.html.twig
<form method="post" action="{{ path('devis_delete', {'id': devi.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ devi.id) }}">
    <button class="btn">Delete</button>
</form>

garage/templates/devis/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

garage/templates/devis/_formDevis.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

garage/templates/devis/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Devis{% endblock %}

{% block body %}
    <h1>Edit Devis</h1>

    {{ include('devis/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('devis_index') }}">back to list</a>

    {{ include('devis/_delete_form.html.twig') }}
{% endblock %}

garage/templates/devis/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Devis index{% endblock %}

{% block body %}
    <style>
        .containerDevis{
            display: flex;
            flex-direction: column;
            justify-content: center;
            margin-top: 7%;
        }
        .styleMessage{
            background-color: aliceblue;
            padding: 3%;
        }
        .category{
            border-bottom: 1px solid black;
            padding-bottom: 3px;
        }
    </style>
    <h1>Devis index</h1>



        <tbody>
        {% for devi in devis %}
            <div class="containerDevis container">
                <div class="styleMessage">
                    <div class="category"><strong>Expediteur: </strong>{{ devi.user }}</div>
                <div class="category"><strong>Voiture: </strong>{{ devi.voiture }}</div>
                <div class="category"><strong>Marque: </strong>{{ devi.marque }}</div>
                <div class="category"><strong>Modèle: </strong>{{ devi.modele }}</div>
                    {% if devi.numero is null %}


                    {% else  %}
                        <div class="category"><strong>Numéro: </strong>{{ devi.numero }}</div>
                    {% endif %}

                <div class="category"><strong>Envoyez le: </strong>{{ devi.date }}</div>
                <div class="category"><strong>Problème technique:  </strong><br>{{ devi.informationComplementaire }}</div>
                <div>
                    <a href="{{ path('devis_show', {'id': devi.id}) }}">show</a>
                    <a href="{{ path('devis_edit', {'id': devi.id}) }}">edit</a>
                </div>

                </div>
            </div>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        <div style="margin-top: 3%;">
        <a  href="{{ path('devis_new') }}">Create new</a>
        </div>
        </tbody>
    {% for AdminReponseDevi in AdminReponseDevi %}
    <div>{{ AdminReponseDevi.user }}</div>
        <div>{{ AdminReponseDevi.message }}</div>
        <div>{{ AdminReponseDevi.estimation }}</div>
        <div class="detailMessage"><a class="detailText"
                                      href="{{ path('reponse_devis', {'id': AdminReponseDevi.id}) }}">Voir le
                message complet</a></div>
    {% endfor %}



{% endblock %}

garage/templates/devis/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Devis{% endblock %}

{% block body %}
    <h1>Create new Devis</h1>

    {{ include('devis/_form.html.twig') }}

    <a href="{{ path('devis_index') }}">back to list</a>
{% endblock %}

garage/templates/devis/newAdmin.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Devis{% endblock %}

{% block body %}
    <h1>Repondre au rendez-vous</h1>


    <div id="my-element"> {{ form_start(form) }}</div>
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
    {{ form_end(form) }}

    {#{{ include('rendez_vous/_formAdmin.html.twig') }}#}



    <a href="{{ path('devis_admin') }}">back to list</a>
{% endblock %}

garage/templates/devis/reponseDevis.html.twig
{% block body  %}

    <tbody>

    <div class="containerDevis container">
        <div class="styleMessage">
            <div class="category"><strong>Expediteur: </strong>Garage Pilet</div>
            <div class="category"><strong>Message: </strong>{{ AdminReponseDevi.Message }}</div>
            <div class="category"><strong>Estimation: </strong>{{ AdminReponseDevi.estimation }}</div>






        </div>
    </div>

    </tbody>

{% endblock %}

garage/templates/devis/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Devis{% endblock %}

{% block body %}
<style>
    .containerDevis{
        display: flex;
        flex-direction: column;
        justify-content: center;
        margin-top: 7%;
    }
    .styleMessage{
        background-color: aliceblue;
        padding: 3%;
    }
    .category{
        border-bottom: 1px solid black;
        padding-bottom: 3px;
    }
</style>
    <h1>Devis</h1>


<tbody>

<div class="containerDevis container">
    <div class="styleMessage">

        <div class="category"><strong>Voiture: </strong>{{ devi.voiture }}</div>
        <div class="category"><strong>Marque: </strong>{{ devi.marque }}</div>
        <div class="category"><strong>Modèle: </strong>{{ devi.modele }}</div>
        {% if devi.numero is null %}


        {% else  %}
            <div class="category"><strong>Numéro: </strong>{{ devi.numero }}</div>
        {% endif %}

        <div class="category"><strong>Envoyez le: </strong>{{ devi.date }}</div>
        <div class="category"><strong>Problème technique:  </strong><br>{{ devi.informationComplementaire }}</div>
        <div>
            <a href="{{ path('devis_index') }}">Retour au devis</a>
            <a href="{{ path('devis_newadmin',{'id': devi.id}) }}">Repondre au rendez-vous</a>
        </div>
        <div>

           <div> {{ include('devis/_delete_form.html.twig') }}</div>
        </div>

    </div>
</div>

</tbody>



{% endblock %}

garage/templates/devis/showDevisAdmin.html.twig
{% extends 'base.html.twig' %}

{% block title %}RendezVous{% endblock %}

{% block body %}
    <style>
        .containerRendezVous{
            margin-top: 10%;
            text-align: center;
            display: flex;
            flex-direction: row;
            justify-content: center;

        }
    </style>
    <h1>Devis</h1>



    <div class="containerRendezVous">
        <div style="width: 60%;
    background-color: cadetblue;
    padding: 10px 10px 10px 10px;
 border: solid 5px black;">
            <h2><strong>Sujet:</strong> Réponse a la demande de devis </h2>
            <div><strong>Message:     </strong>{{ AdminReponseDevis.message }}</div>
        </div>
    </div>



{% endblock %}